[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

[invariant]
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
